### PR TITLE
Update output

### PR DESCRIPTION
**Pull request by ClemensBuechner**
- Remove logging of "Obtaining successor" message.
- Log modification message.

### CODE REVIEW

**Comment by FlorianPommerening** [comment]
I had a quick look at the changes. I would prefer if we wouldn't have to put the message into the state but I'm also fine with leaving it like this if you like this better. The alternative would be to return a tuple of a state and a message. The code around that then would have to deal with this tuple which probably is a larger change but I think a cleaner design because the change message is not conceptually part of the state.

**Comment by FlorianPommerening** [comment]
Also, since this is an internal change, we could also just go ahead with this change for now and possibly refactor later.

**Comment by ClemensBuechner** [comment]
I agree that the change message does not belong to the state and another solution is probably nicer. I would prefer to address this right away, but I'm struggling to find a good solution. I'm following your idea to require from successor generators a pair `<successor, msg>`. Now which part should take care of the message? Do we pass them into the enviornments together with the successors (e.g., just pass along a batch of tuples instead of a batch of successors)? But then is it the environment's responsibility to print the message, or does it simply ignore it? Or rather, return it together with the improving successor once queried for it? I guess that's the way to go, but it seems somewhat bulkier than what we had before, because now the environments have this implicit knowledge that a successor is a tuple of state and message, even though they only pass it on, which is somewhat similar to enlarging the state dictionary itself with the change message (as in commit [71146bd](https://github.com/aibasel/machetli/pull/47/commits/71146bd72d24258d573a4c6559568ff9fdd362c7)).

**Comment by FlorianPommerening** [comment]
I think passing it along through the environment and letting the search handle it would be best. If you dislike having tuples everywhere, we could wrap this in a new class `Successor` that holds a state and a success message. Then all code that currently passes around a successor state would now pass around a `Successor` instead. This would make the implicit knowledge that the environments need a bit more explicit.

**Comment by ClemensBuechner** [comment]
I thought about introducing a new class `Successor`, but wasn't too convinced at first. Now that I think about it again, it seems to be the best option to me for now. I'll implement the necessary changes.

**Pull request merged**
